language: python
python:
  - "3.4"
  - "3.5"

before_install:
  - ./include/boblight/install_boblight.sh

install:
  - python setup.py install

script: 
  - python setup.py test

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
